Repository guide-on/frontend, pull requests merged in 2025-09, with the labels that each got.

#6 로그인/로그아웃 프론트 연동 및 구현
  src/App.tsx
  src/api/index.ts
  src/api/memberApi.ts
  src/api/verificationApi.ts
  src/components/auth/BusinessCertUploadSheet.tsx
  src/components/auth/FindId.tsx
  src/components/auth/FindPw.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/TermsAgreement.tsx
  src/components/verification/EmailVerificaition.tsx
  src/components/verification/PhoneVerification.tsx
  src/index.css
  src/pages/MyPage.tsx
  src/pages/auth/FindIdPw.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Signup.tsx
  src/stores/useAuthStore.ts
Labels: ✨ feature, 🎨 design

#18 feat: 회원가입 프론트 연동 및 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/bizApi.ts
  src/api/industryApi.ts
  src/api/memberApi.ts
  src/api/regionApi.ts
  src/components/auth/FindId.tsx
  src/components/auth/FindPw.tsx
  src/components/auth/KsicModal.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/TermsAgreement.tsx
  src/components/auth/signup/StepAccount.tsx
  src/components/auth/signup/StepBusiness.tsx
  src/components/auth/signup/StepProfile.tsx
  src/components/auth/signup/StepTerms.tsx
  src/components/auth/signup/StepType.tsx
  src/components/common/LoadingOverlay.tsx
  src/components/common/Pagination.tsx
  src/components/verification/EmailVerificaition.tsx
  src/components/verification/PhoneVerification.tsx
  src/pages/auth/FindIdPw.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Onboarding.tsx
  src/pages/auth/Signup.tsx
  src/stores/useSignupStore.ts
  src/utils/signup.ts
Labels: ✨ feature, 🎨 design

#20 feat : 서류 등록 페이지 구현
  builder.config.json
  src/App.tsx
  src/api/documentApi.ts
  src/components/auth/MydataConsentModal.tsx
  src/components/common/Header.tsx
  src/guide/pages/DocumentSurveyPage.tsx
  src/guide/pages/DocumentUploadPage.tsx
  src/guide/pages/MydataConsentPage.tsx
  src/guide/pages/MydataSyncComplete.tsx
  src/guide/pages/PolicyListPage.tsx
  src/guide/pages/RequiredDocumentsPage.tsx
  src/index.css
Labels: ✨ feature, 🎨 design

#24 Feat/#15 home design fix
  src/App.tsx
  src/assets/3d/logo.png
  src/assets/3d/zoom-dynamic-color.png
  src/assets/logo/bulb.png
  src/assets/logo/logo.png
  src/components/common/SplashScreen.tsx
  src/home/components/GuideStatusCarousel.tsx
  src/home/components/GuideStatusSlideCard.tsx
  src/home/components/HomeGreeting.tsx
  src/home/components/HomeHero.tsx
  src/home/components/HomeStatsRow.tsx
  src/home/components/RichLinkCard.tsx
  src/home/components/SectionTitleRow.tsx
  src/home/pages/Home.tsx
  src/home/utils/mock.ts
  src/styles/colors.ts
Labels: ✨ feature, 🎨 design

#25 Fix : 마이데이터 연동 시 서류 조회 오류 해결
  src/App.tsx
  src/api/documentApi.ts
  src/guide/pages/DocumentUploadPage.tsx
  src/guide/pages/PolicyListPage.tsx
  src/guide/pages/RequiredDocumentsPage.tsx
Labels: 🐛 bugfix

#28 feat: 맞춤 공고 기능 구현
  src/api/announcementApi.ts
  src/api/fundApi.ts
  src/components/support/AnnouncementCard.tsx
  src/components/support/AnnouncementDetailModal.tsx
  src/components/support/AnnouncementsList.tsx
  src/components/support/FilterButtons.tsx
  src/components/support/FilterSheet.tsx
  src/components/support/FundCard.tsx
  src/components/support/FundDetailModal.tsx
  src/components/support/MapView.tsx
  src/components/support/SearchForm.tsx
  src/components/support/SupportCenterCard.tsx
  src/pages/Support.tsx
  src/styles/support.css
  src/types/support.ts
Labels: ✨ feature

#33 feat: 레이아웃 개선
  index.html
  public/images/logo.png
  src/App.tsx
  src/community/pages/CaseList.tsx
  src/community/pages/FreeboardList.tsx
  src/community/pages/PostDetail.tsx
  src/community/pages/PostEdit.tsx
  src/components/auth/signup/StepAccount.tsx
  src/components/auth/signup/StepBusiness.tsx
  src/components/auth/signup/StepProfile.tsx
  src/components/auth/signup/StepTerms.tsx
  src/components/auth/signup/StepType.tsx
  src/components/common/Header.tsx
  src/components/common/LoadingOverlay.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/Navbar.tsx
  src/components/support/AnnouncementsList.tsx
  src/components/support/FilterSheet.tsx
  src/components/support/FundsList.tsx
  src/components/support/KakaoMap.tsx
  src/components/support/MapView.tsx
  src/components/support/PlaceDetailModal.tsx
  src/components/support/SupportCenterCard.tsx
  src/components/verification/EmailVerificaition.tsx
  src/components/verification/PhoneVerification.tsx
  src/home/pages/Home.tsx
  src/index.css
  src/pages/Hybrid Evaluation/Result.tsx
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
  src/pages/auth/FindIdPw.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Onboarding.tsx
  src/pages/auth/Signup.tsx
  src/simulation/pages/SimulationDetail.tsx
  src/simulation/pages/SimulationList.tsx
Labels: ✨ feature, 🎨 design

#35 refactor: esg 컴포넌트화
  src/home/pages/Home.tsx
  src/pages/Hybrid Evaluation/Start.tsx
  src/pages/Hybrid Evaluation/components/EsgSection.tsx
  src/pages/Hybrid Evaluation/components/EsgStepSection.tsx
  src/pages/Hybrid Evaluation/components/EsgSteps.tsx
  src/pages/Hybrid Evaluation/components/UploadCard.tsx
  src/pages/Hybrid Evaluation/index.tsx
Labels: 🔁 refactor
